import React, { useState } from 'react';
import { Bot, Play, CheckCircle2, Smartphone, Code, Layers, Sparkles, MessageSquare, ArrowRight, RefreshCw, Terminal, Check } from 'lucide-react';

interface PresetApp {
  id: string;
  name: string;
  tagline: string;
  category: string;
  features: string[];
  screens: {
    title: string;
    items: string[];
    action: string;
  };
  sampleCode: string;
}

export const AiAppBuilderWorkflow: React.FC = () => {
  const presetApps: PresetApp[] = [
    {
      id: 'clinic',
      name: 'Doctor & Clinic Appointment App',
      tagline: 'Patients book slots in seconds; doctors get live daily schedule',
      category: 'Healthcare & Local Clinic',
      features: [
        '1-Tap patient appointment booking',
        'Automatic WhatsApp appointment reminder',
        'Doctor digital prescription maker',
        'Patient history & lab test uploads',
      ],
      screens: {
        title: 'City Health Clinic',
        items: [
          'Dr. Sharma — Cardiologist (Available 4:00 PM)',
          'Dr. Priya — Dentist (Available 5:30 PM)',
          'Book Instant Slot & Pay with UPI',
        ],
        action: 'Confirm Appointment',
      },
      sampleCode: `// Generated by AI Agent
class ClinicApp extends StatefulWidget {
  Future<void> bookDoctorSlot(String doctorId, String patientPhone) async {
    final slot = await Database.reserveSlot(doctorId, Time.now());
    await WhatsAppAgent.sendConfirmation(patientPhone, slot.time);
  }
}`,
    },
    {
      id: 'store',
      name: 'Local Store Billing & WhatsApp Order App',
      tagline: 'Customers browse items on mobile, orders arrive directly on WhatsApp',
      category: 'Retail & Grocery Store',
      features: [
        'Simple product catalog with photos and prices',
        'Direct "Order on WhatsApp" 1-click checkout',
        'Daily sales report & inventory alerts',
        'Works offline even without fast internet',
      ],
      screens: {
        title: 'Fresh Grocery Mart',
        items: [
          'Organic Basmati Rice 5kg — ₹380',
          'Pure Cow Ghee 500ml — ₹320',
          'Daily Fresh Farm Milk 1L — ₹65',
        ],
        action: 'Send Order to WhatsApp (₹765)',
      },
      sampleCode: `// Generated by AI Agent
function createWhatsAppOrder(cartItems, customerPhone) {
  const summary = cartItems.map(i => \`• \${i.name} (x\${i.qty})\`).join('\\n');
  return WhatsApp.sendToStoreOwner({
    text: \`New Order Received!\\n\${summary}\\nTotal: ₹\${calculateTotal(cartItems)}\`
  });
}`,
    },
    {
      id: 'gym',
      name: 'Gym & Fitness Membership App',
      tagline: 'Members check in with QR, track workouts, and renew memberships',
      category: 'Fitness & Sports Club',
      features: [
        'Digital QR code entry pass for members',
        'Daily workout routine & diet plan view',
        'Automatic fee renewal reminders on WhatsApp',
        'Trainer personal chat & progress photos',
      ],
      screens: {
        title: 'Iron Core Fitness Club',
        items: [
          'Membership: Active (Expires in 18 days)',
          'Today\'s Goal: Chest & Triceps (4 Exercises)',
          'QR Entry Pass: [ SCAN AT TURNSTILE ]',
        ],
        action: 'Renew 3-Month Plan (₹2,999)',
      },
      sampleCode: `// Generated by AI Agent
const MemberEntryPass = ({ memberId }) => {
  const qrToken = useSecureEntryToken(memberId);
  return <QRDisplay code={qrToken} onGateScan={() => logAttendance(memberId)} />;
};`,
    },
  ];

  const [selectedApp, setSelectedApp] = useState<PresetApp>(presetApps[0]);
  const [customIdea, setCustomIdea] = useState('');
  const [activeStep, setActiveStep] = useState<number>(0);
  const [isBuilding, setIsBuilding] = useState<boolean>(false);
  const [logs, setLogs] = useState<string[]>([
    'Click "Watch AI Agent Build This App" to see the step-by-step creation process.'
  ]);

  const workflowSteps = [
    {
      num: '01',
      title: 'Step 1: You Describe Your App Idea',
      simpleExplain: 'No technical jargon. You just speak or type what you need in plain words (e.g. "I want an app for my grocery store to get orders on WhatsApp").',
      agentAction: 'AI Agent analyzes your needs, plans the user screens, and lists required features.',
    },
    {
      num: '02',
      title: 'Step 2: AI Agent Designs The Screens',
      simpleExplain: 'The AI Agent automatically creates colorful, easy-to-use screens for phones and tablets that your customers will love.',
      agentAction: 'AI Agent generates high-quality buttons, layouts, clean fonts, and product views.',
    },
    {
      num: '03',
      title: 'Step 3: AI Agent Writes The Code',
      simpleExplain: 'Instead of weeks of manual typing, the AI Agent writes clean, secure code connecting databases, login, and payments.',
      agentAction: 'AI Agent generates mobile app code (Flutter/React Native) with local database and cloud sync.',
    },
    {
      num: '04',
      title: 'Step 4: AI Agent Tests & Fixes Bugs',
      simpleExplain: 'The AI runs hundreds of automatic checks to make sure the app never crashes, runs fast, and works even on slow Wi-Fi.',
      agentAction: 'AI Agent executes simulated user taps, verifies memory usage, and eliminates errors.',
    },
    {
      num: '05',
      title: 'Step 5: Ready for Play Store & Your Phone',
      simpleExplain: 'Senior engineer Srikanth gives it a final human polish, tests it on real devices, and hands you the ready-to-use app.',
      agentAction: 'App is compiled into an APK/Play Store download ready for real customers.',
    },
  ];

  const handleStartBuild = () => {
    if (isBuilding) return;
    setIsBuilding(true);
    setActiveStep(1);
    setLogs([`Starting AI Agent App Builder for: "${selectedApp.name}"...`]);

    const stepsToRun = [
      { step: 1, text: 'Step 1 [Planning]: AI Agent mapped 4 core features and created user flow blueprint.' },
      { step: 2, text: 'Step 2 [Design]: AI Agent crafted mobile UI layouts, color palettes, and buttons.' },
      { step: 3, text: 'Step 3 [Code Generation]: AI Agent generated 1,450 lines of tested code & database schema.' },
      { step: 4, text: 'Step 4 [Bug Testing]: AI Agent simulated 50 user actions — 0 errors found.' },
      { step: 5, text: 'Step 5 [Complete!]: Working mobile app ready to install on Android & iOS.' },
    ];

    stepsToRun.forEach((s, idx) => {
      setTimeout(() => {
        setActiveStep(s.step);
        setLogs((prev) => [...prev, s.text]);

        if (idx === stepsToRun.length - 1) {
          setTimeout(() => {
            setIsBuilding(false);
            setLogs((prev) => [
              ...prev,
              '🎉 Success! Your custom app is ready to test. Send your requirements to Srikanth to get started!'
            ]);
          }, 600);
        }
      }, (idx + 1) * 850);
    });
  };

  const handleWhatsAppInquiry = () => {
    const text = encodeURIComponent(
      `Hi Srikanth, I watched the AI Agent App Workflow on Shristi Tech. I want to build a custom app: "${customIdea || selectedApp.name}". Can we discuss the timeline?`
    );
    window.open(`https://wa.me/917013707890?text=${text}`, '_blank');
  };

  return (
    <section id="ai-app-workflow" className="py-20 bg-slate-900 text-white border-b border-slate-800 relative overflow-hidden">
      {/* Background ambient lighting */}
      <div className="absolute top-0 right-10 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-10 left-10 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Header */}
        <div className="max-w-3xl mb-12">
          <div className="flex items-center gap-2 text-xs font-mono font-semibold text-blue-400 uppercase tracking-wider mb-2">
            <Bot className="w-4 h-4 text-blue-400" />
            <span>AI Agent App Development Workflow</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-display font-extrabold text-white tracking-tight">
            How AI Agents Build Your Custom App in Days
          </h2>
          <p className="text-sm sm:text-base text-slate-300 mt-3 leading-relaxed">
            In the past, building a custom mobile app took 4 months and cost a fortune. Today, our specialized <strong>AI Agents</strong> do the heavy lifting — writing code, designing screens, and testing features at lightning speed, guided by human engineering.
          </p>
        </div>

        {/* Step Selector / App Idea Tabs */}
        <div className="bg-slate-950 p-4 rounded-2xl border border-slate-800 mb-8">
          <div className="text-xs font-mono text-slate-400 uppercase tracking-wider mb-3">
            Pick an example app idea to simulate, or type your own:
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {presetApps.map((app) => (
              <button
                key={app.id}
                onClick={() => {
                  setSelectedApp(app);
                  setActiveStep(0);
                  setIsBuilding(false);
                  setLogs([`Selected: "${app.name}". Click "Watch AI Agent Build This App" to run simulation.`]);
                }}
                className={`p-3.5 rounded-xl border text-left transition-all ${
                  selectedApp.id === app.id
                    ? 'bg-blue-600/20 border-blue-500 text-white ring-1 ring-blue-500'
                    : 'bg-slate-900 border-slate-800 text-slate-400 hover:text-slate-200 hover:border-slate-700'
                }`}
              >
                <div className="text-[10px] font-mono text-blue-400 uppercase font-semibold">{app.category}</div>
                <div className="text-xs font-bold text-white mt-1 leading-snug">{app.name}</div>
                <div className="text-[11px] text-slate-400 mt-1 line-clamp-1">{app.tagline}</div>
              </button>
            ))}
          </div>

          {/* Custom App input */}
          <div className="mt-4 pt-3 border-t border-slate-800/80 flex flex-col sm:flex-row gap-3">
            <input
              type="text"
              placeholder="Or type your own app idea (e.g. Real Estate Property App, Restaurant Menu App)..."
              value={customIdea}
              onChange={(e) => setCustomIdea(e.target.value)}
              className="flex-1 bg-slate-900 border border-slate-700 rounded-xl px-4 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
            />
            <button
              onClick={handleStartBuild}
              disabled={isBuilding}
              className="px-5 py-2.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white text-xs font-bold rounded-xl shadow-lg flex items-center justify-center gap-2 transition-all active:scale-95 whitespace-nowrap"
            >
              {isBuilding ? (
                <>
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>AI Agent Is Building...</span>
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5 fill-current" />
                  <span>Watch AI Agent Build This App</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* The 5-Step Workflow Grid with Live Phone Simulator */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Left Column: 5 Sequential Workflow Steps (7 cols) */}
          <div className="lg:col-span-7 space-y-3">
            {workflowSteps.map((step, idx) => {
              const stepNumber = idx + 1;
              const isCurrent = activeStep === stepNumber;
              const isFinished = activeStep > stepNumber;

              return (
                <div
                  key={idx}
                  className={`p-4 rounded-xl border transition-all duration-300 flex items-start gap-4 ${
                    isCurrent
                      ? 'bg-blue-950/80 border-blue-500 shadow-lg shadow-blue-500/20 ring-1 ring-blue-500 scale-[1.01]'
                      : isFinished
                      ? 'bg-slate-950/80 border-emerald-500/60'
                      : 'bg-slate-950/40 border-slate-800 opacity-75'
                  }`}
                >
                  <div
                    className={`w-9 h-9 rounded-xl flex items-center justify-center font-mono font-bold text-xs flex-shrink-0 transition-colors ${
                      isFinished
                        ? 'bg-emerald-500 text-white'
                        : isCurrent
                        ? 'bg-blue-500 text-white animate-pulse'
                        : 'bg-slate-800 text-slate-400'
                    }`}
                  >
                    {isFinished ? <Check className="w-4 h-4 stroke-[3]" /> : step.num}
                  </div>

                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <h4 className="text-sm font-bold text-white leading-snug">{step.title}</h4>
                      <span className="text-[10px] font-mono text-slate-400">
                        {isFinished ? 'Completed' : isCurrent ? 'Active Now' : 'Pending'}
                      </span>
                    </div>

                    <p className="text-xs text-slate-300 mt-1 leading-relaxed">
                      {step.simpleExplain}
                    </p>

                    <div className="mt-2 text-[11px] font-mono text-blue-300/90 flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-blue-400" />
                      <span>{step.agentAction}</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Right Column: Live App Preview & Smartphone Simulation (5 cols) */}
          <div className="lg:col-span-5 flex flex-col items-center">
            {/* Phone Screen Mockup */}
            <div className="w-full max-w-[310px] bg-slate-950 border-4 border-slate-700 rounded-[36px] p-4 shadow-2xl relative">
              {/* Notch */}
              <div className="w-24 h-4 bg-slate-800 rounded-full mx-auto mb-3" />

              {/* Phone Display */}
              <div className="bg-slate-900 rounded-2xl p-4 min-h-[380px] flex flex-col justify-between border border-slate-800">
                {/* App Header */}
                <div>
                  <div className="flex items-center justify-between border-b border-slate-800 pb-2 mb-3">
                    <div>
                      <div className="text-[10px] font-mono text-blue-400 uppercase font-bold">
                        {customIdea ? 'Custom Solution' : selectedApp.category}
                      </div>
                      <div className="text-xs font-bold text-white truncate max-w-[160px]">
                        {customIdea || selectedApp.screens.title}
                      </div>
                    </div>
                    <span className="text-[9px] bg-emerald-500/20 text-emerald-400 px-2 py-0.5 rounded border border-emerald-500/30">
                      Live Preview
                    </span>
                  </div>

                  {/* App Screen Content */}
                  <div className="space-y-2">
                    {selectedApp.screens.items.map((item, i) => (
                      <div
                        key={i}
                        className="p-2.5 rounded-lg bg-slate-800/80 border border-slate-700 text-[11px] text-slate-200 flex items-center gap-2"
                      >
                        <span className="w-2 h-2 rounded-full bg-blue-400 flex-shrink-0" />
                        <span className="truncate">{item}</span>
                      </div>
                    ))}
                  </div>

                  {/* Feature Checkpoints */}
                  <div className="mt-4 pt-3 border-t border-slate-800/80 space-y-1.5">
                    <div className="text-[9px] font-mono uppercase text-slate-400 font-semibold">
                      Automated Features Built:
                    </div>
                    {selectedApp.features.map((feat, i) => (
                      <div key={i} className="text-[10px] text-slate-300 flex items-center gap-1.5">
                        <CheckCircle2 className="w-3 h-3 text-emerald-400 flex-shrink-0" />
                        <span className="truncate">{feat}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Primary App Button */}
                <div className="pt-4">
                  <button
                    onClick={() => alert(`This is an interactive simulation of ${selectedApp.name}. Srikanth can build this custom for your business!`)}
                    className="w-full py-2.5 px-3 bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs rounded-xl shadow-md transition-all active:scale-95 truncate"
                  >
                    {selectedApp.screens.action}
                  </button>
                </div>
              </div>

              {/* Bottom Phone Bar */}
              <div className="w-20 h-1 bg-slate-700 rounded-full mx-auto mt-3" />
            </div>

            {/* Live Agent Terminal Log */}
            <div className="w-full max-w-[310px] mt-4 bg-black/80 rounded-xl p-3 border border-slate-800 font-mono text-[11px] text-slate-300">
              <div className="flex items-center justify-between pb-1.5 mb-1.5 border-b border-slate-800 text-slate-400 text-[10px]">
                <div className="flex items-center gap-1.5">
                  <Terminal className="w-3 h-3 text-blue-400" />
                  <span>Agent Build Console</span>
                </div>
                <span className="text-emerald-400">{isBuilding ? 'Running...' : 'Ready'}</span>
              </div>
              <div className="max-h-24 overflow-y-auto space-y-1">
                {logs.map((log, i) => (
                  <div key={i} className="leading-snug">
                    <span className="text-blue-400 mr-1">&gt;</span>
                    {log}
                  </div>
                ))}
              </div>
            </div>

            {/* Direct CTA */}
            <div className="w-full max-w-[310px] mt-3">
              <button
                onClick={handleWhatsAppInquiry}
                className="w-full py-2.5 px-3 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl flex items-center justify-center gap-2 shadow-lg transition-all active:scale-95"
              >
                <MessageSquare className="w-3.5 h-3.5" />
                <span>Build This App on WhatsApp</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
